# Generated by Django 5.0.7 on 2024-09-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='description',
            field=models.CharField(help_text='no more than 150 chars', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='departments',
            unique_together={('name', 'dept_branch')},
        ),
    ]
